### ISSUE TITLE
Plugin not available for Starter Access

### ISSUE THREAD

**Issue by jwsmith0731** [ElRubioLoco/HowManyContenders#8]
My settings in openplanet are set, so it should always be showing, but it never shows up anywhere on my screen. There is no error message or anything, just doesn't appear. Would appreciate potential solutions, thank you!

**Comment by ElRubioLoco** [comment]
Hi @jwsmith0731 ! Thank you for your report, the plugin shows up only while you're playing a track, if you try to see it in the menus, it won't show up.
## Troubleshooting
If it doesn't show up while you're on a track:
1. there is a show/hide button in the plugin's configuration ```'Plugins' tab > How Many Contenders```. Maybe you've set it to ***hide*** ?
2. A new version of the plugin came out couple hours ago. Are you on the last version of the plugin ?
> Last version of the plugin is 1.1
### If all the previous steps don't apply, there is an error somewhere. Let's find it.
1. Try opening log window ```'Openplanet' tab > Log```.
![image](https://github.com/ElRubioLoco/HowManyContenders/assets/71330833/09343637-607e-4003-ad28-6e9b72df8ea7)
2. Once the log window is open, if there is an error, you should see some red messages in it.
3. If you don't see any, try to reload the plugin while you have the log window open.
> Go to ```'Developer' tab > Reload plugin > How Many Contenders```

If you see any error message, take a screen capture and post it in this issue. If you don't, tell me also and we'll figure out how can we solve this.

Let me know if you have any question or if you don't understand a step.

**Comment by jwsmith0731** [comment]
I checked all my settings and checked it in a track and everything looked as you described, and no errors were in the log. When I reloaded the plug-in the only thing that came up in the log was waiting for permissions as seen below.
![image](https://github.com/ElRubioLoco/HowManyContenders/assets/139193235/665442e1-12ba-4d98-83d3-25c2a33e4bf0)

**Comment by ElRubioLoco** [comment]
Ok I see, Are you in **starter access** ?

I'm currently seeing with **openplanet community** and **Nadeo** to know if I can put this plugin available to users just having starter acces, but it's currently not the case.

**Comment by ElRubioLoco** [comment]
I'm gonna submit an open version this evening, we'll see how it goes. I'll let you know as soon as I have an answer !

**Comment by jwsmith0731** [comment]
I am unfortunately on starter access, I was not aware it wasn't available with starter access. Thank you for the help though, i appreciate it!

**Comment by ElRubioLoco** [comment]
Hi @jwsmith0731 !

I have the pleasure to tell you that my plug-in has been accepted by OpenPlanet! 

It is now open to users with starter access.

You can use it with 1.2 version available in the plugin manager.

Have fun!
